# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint, test, build and push to Github Container Registery

on:
  push:
    branches: [ "master" ]
  

permissions:
  contents: read
  packages: write 

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Listing files 
      run: ls -la && pwd
    - name: Install dependencies from requirements file 
      run: pip install -r requirements.txt
    - name: Check and fix code lint using ruff linter
      run: python -m ruff check .
    - name: Test with pytest
      run: pytest

    # Login to GitHub Container Registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with: 
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    # # Push image to GitHub Container Registry
    # - name: Build and push to GitHub Container Registery 
    #   uses: docker/build-push-action@v6
    #   with: 
    #     push: true
    #     tags: ghcr.io/fredoom03/FastAPI-GitHub-Actions:latest
